# Generated by Django 2.1.4 on 2019-06-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
